your_developer_username: jenkins
your_developer_password: jenkins123
your_developer_email: myapp-developer@test.com

registry_domain: "3-99-131-82.sslip.io"
nexus_public_url: "https://{{ registry_domain }}"
















