role_name: "myapp-developer-role"
your_developer_username: jenkins
your_developer_password: jenkins123
your_developer_email: myapp-developer@test.com
nexus_base_url: "http://10.0.10.209:8081"

















