- name: Create blobstores
  cloudkrafter.nexus.nexus_blobstore:
    name: "{{ item.name }}"
    type: file
    path: "{{ item.path }}"
    state: present
    nexus_url: "{{ nexus_url }}"
    nexus_username: "{{ nexus_username }}"
    nexus_password: "{{ nexus_password }}"
  loop: "{{ blobstores }}"
