- name: Create Jenkins Nexus user
  cloudkrafter.nexus.nexus_user:
    username: jenkins
    password: "{{ jenkins_password }}"
    first_name: Jenkins
    last_name: CI
    roles:
      - jenkins-ci-role
    state: present
    nexus_url: "{{ nexus_url }}"
    nexus_username: "{{ nexus_username }}"
    nexus_password: "{{ nexus_password }}"
