    nexus_private_ip: "10.0.10.131"          # internal IP of the Nexus server
    nexus_hostname: "35-183-182-201.sslip.io" # Replace with your public DNS, i.e nginx DNS
    keystore_pass: "changeit"
    key_alias: "nexus"