- debug:
    var: hostvars[groups['k8s_master'][0]].join_command


- name: Join worker to cluster
  command: "{{ hostvars[groups['k8s_master'][0]].join_command }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: inventory_hostname not in hostvars[groups['k8s_master'][0]].kubectl_get_nodes.stdout_lines
