registry_domain: repo.vinny-dev.com
nexus_upstream_host: 10.0.10.156
nexus_upstream_port: 8081
docker_group_repo: myapp-docker-group
docker_hosted_repo: myapp-docker-hosted
letsencrypt_email: admin@repo.vinny-dev.com


# MUST Use Separate Subdomain, Best practice:
# nexus.example.com      → Nexus UI
# registry.example.com   → Docker registry
