nexus_upstream_host: "10.0.10.236"          # internal IP of the Nexus server
nexus_upstream_port: 8081
registry_domain: repo.vinny-dev.com # Replace with your DNS pointing to nginx ip
letsencrypt_email: admin@repo.vinny-dev.com
enable_docker_subdomain: true
docker_registry_domain: registry.example.com # Replace with your subdomain pointing to nginx ip


# MUST Use Separate Subdomain, Best practice:
# nexus.example.com      → Nexus UI
# registry.example.com   → Docker registry
