nexus_url: "http://10.0.10.147:8081"
nexus_username: "admin"
nexus_password: "admin123"

jenkins_password: "JenkinsNexus123!"

blobstores:
  - name: maven-blobstore
    path: maven
  - name: npm-blobstore
    path: npm
  - name: pypi-blobstore
    path: pypi
  - name: docker-blobstore
    path: docker

nexus_repositories:

  ## ===========================
  ## MAVEN
  ## ===========================
  - name: maven-central-proxy
    format: maven2
    type: proxy
    remote_url: "https://repo1.maven.org/maven2/"
    blob_store: maven-blobstore

  - name: maven-releases
    format: maven2
    type: hosted
    version_policy: release
    write_policy: allow
    blob_store: maven-blobstore

  - name: maven-snapshots
    format: maven2
    type: hosted
    version_policy: snapshot
    write_policy: allow
    blob_store: maven-blobstore

  - name: maven-public
    format: maven2
    type: group
    members:
      - maven-releases
      - maven-snapshots
      - maven-central-proxy

  ## ===========================
  ## NPM
  ## ===========================
  - name: npm-proxy
    format: npm
    type: proxy
    remote_url: "https://registry.npmjs.org"
    blob_store: npm-blobstore

  - name: npm-hosted
    format: npm
    type: hosted
    write_policy: allow
    blob_store: npm-blobstore

  - name: npm-group
    format: npm
    type: group
    members:
      - npm-proxy
      - npm-hosted

  ## ===========================
  ## PYPI
  ## ===========================
  - name: pypi-proxy
    format: pypi
    type: proxy
    remote_url: "https://pypi.org"
    blob_store: pypi-blobstore

  - name: pypi-hosted
    format: pypi
    type: hosted
    write_policy: allow
    blob_store: pypi-blobstore

  - name: pypi-group
    format: pypi
    type: group
    members:
      - pypi-proxy
      - pypi-hosted

  ## ===========================
  ## DOCKER
  ## ===========================
  - name: docker-hosted
    format: docker
    type: hosted
    http_port: 5000
    enable_v1: true
    write_policy: allow
    blob_store: docker-blobstore

