---
- name: Ensure keyring directory exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"

- name: Download Jenkins GPG key (2026 key, ASCII armored)
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: "0644"

- name: Add Jenkins apt repository (ASCII key, no dearmor)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java 21 and fontconfig
  apt:
    name:
      - fontconfig
      - openjdk-21-jdk
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes


- name: Wait for Jenkins to start
  wait_for:
    port: 8080
    delay: 10

- name: Get Jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password
  failed_when: false 
  changed_when: false

- name: Display Jenkins password
  debug:
    msg: "Jenkins initial password: {{ jenkins_password.stdout }}"

- name: Install Docker for Jenkins
  include_role:
    name: docker

- name: Install Docker Engine and CLI
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Add Ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install kubectl for Jenkins
  get_url:
    url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Install python3-pip
  apt:
    name: -y python3-venv python3-pip
    state: present  

# - name: Create Jenkins .kube directory
#   file:
#     path: /var/lib/jenkins/.kube
#     state: directory
#     owner: jenkins
#     group: jenkins
#     mode: '0700'

# - name: Fetch admin.conf from Kubernetes master
#   fetch:
#     src: /etc/kubernetes/admin.conf       # path on k8s master
#     dest: /tmp/admin.conf                  # path on Ansible controller
#     flat: yes                              # saves directly as /tmp/admin.conf
#   delegate_to: k8s-master-1
#   run_once: true  

# - name: Copy kubeconfig to Jenkins
#   copy:
#     src: /tmp/admin.conf  # Fetched from master
#     dest: /var/lib/jenkins/.kube/config
#     owner: jenkins
#     group: jenkins
#     mode: '0600'
