registry_domain: "3-98-125-121.sslip.io"  # ← Input: proxy server domain registry  
cert_src: "/tmp/nexus.crt"       # ← Input: e.g., /tmp/nexus.crt (copy from proxy first to bastion host 
docker_certs_dir: "/etc/docker/certs.d/{{ registry_domain }}"
docker_registry_username: "{{ vault_nexus_user_username }}"
docker_registry_password: "{{ vault_nexus_user_password }}"


# Log into the proxy host from the bastion host, then manually copy the file at this path /etc/nginx/certs/nexus.crt
# from the proxy to the Docker client (Jenkins server) at this path:
# /tmp/nexus.crt
