nexus_private_ip: "10.0.10.131"          # internal IP of the Nexus server
registry_domain: "35-182-161-35.sslip.io" # Replace with your public DNS, i.e nginx DNS
keystore_pass: "changeit"
key_alias: "nexus"
docker_hosted_repo: "myapp-docker-hosted"
docker_group_repo: "myapp-docker-group"

