nexus_server_ip: "10.0.10.91"          # internal IP of the Nexus server
registry_domain: "3-98-125-121.sslip.io" # Replace with your public DNS, i.e nginx DNS
keystore_pass: "changeit"
key_alias: "nexus"
docker_hosted_repo: "myapp-docker-hosted"
docker_group_repo: "myapp-docker-group"
Public_certificate_path: "/etc/nginx/certs/nexus.crt"
Private_key_path: "/etc/nginx/certs/nexus.key"

